# .github/workflows/main.yml

name: Trigger Netlify Build
on:
  schedule:
    # Run at 18h daily
    - cron: '0 15 * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/6011718357c0b68243d01cc0
