# .github/workflows/main.yml

name: Trigger Netlify Build
uses: zcong1993/setup-timezone@master
with:
    timezone: Asia/Shanghai
on:
  schedule:
    # Run at 0815 daily
    - cron: '15 21 * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/6011718357c0b68243d01cc0